# Generated by Django 3.2.12 on 2022-02-08 07:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_price', models.FloatField(max_length=6)),
                ('qty', models.IntegerField()),
                ('total_price', models.FloatField(max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 2, 8, 13, 26, 7, 605379))),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
